#!/bin/bash
#
# chkconfig:   3 90 10
#
### BEGIN INIT INFO
# Provides:          redbox
# Default-Stop:      0 1 6
# Short-Description: Researchdata ReDBox Daemon
# description:       Web Server running 3rd-party "The Fascinator - ReDBox" service
#                    Research Data Metadata Store Project.
#                    Accessible http://researchdata-dev.its.deakin.edu.au:80
# processname:       /opt/researchdata/redbox/server/tf.sh
#                    ** this command will look after {start|stop|restart|status} ops
# config:            /opt/researchdata/redbox/server/tf_env.sh
### END INIT INFO

/opt/researchdata/redbox/server/tf.sh $1

